# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('where', models.CharField(blank=True, max_length=200)),
                ('time_frame', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('where', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('time_frame', models.CharField(blank=True, max_length=200)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, choices=[(b'', b''), (b'Native', b'Native'), (b'Fluent', b'Fluent'), (b'Intermediate', b'Intermediate'), (b'Basic', b'Basic')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_style', models.CharField(choices=[(b'styles.css', b'Blue'), (b'styles-2.css', b'Green-Blue'), (b'styles-3.css', b'Green'), (b'styles-4.css', b'Purple'), (b'styles-5.css', b'Orange'), (b'styles-6.css', b'Dark-Blue')], default=b'styles.css', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('profile_img_url', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('footer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('me_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv.Me')),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='me_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv.Me'),
        ),
        migrations.AddField(
            model_name='interest',
            name='me_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='cv.Me'),
        ),
        migrations.AddField(
            model_name='extrasection',
            name='me_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_sections', to='cv.Me'),
        ),
        migrations.AddField(
            model_name='experience',
            name='me_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='cv.Me'),
        ),
        migrations.AddField(
            model_name='education',
            name='me_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='cv.Me'),
        ),
        migrations.AddField(
            model_name='contactref',
            name='me_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_refs', to='cv.Me'),
        ),
    ]
